import { pgEnum } from "drizzle-orm/pg-core";

/**
 * File-upload (Vercel Blob) — shared enums.
 *
 * Capability: `file-upload.data-model` (PB-FILE-DATA-001 / BBR-547).
 * EXTEND of `product-builder-base` file-upload capability — see
 * doc/plans/PB-FILE-001-vercel-blob-file-upload-scope.md for the locked
 * access/retention/status policy these enums encode.
 *
 * The base `files` table (packages/drizzle/src/schema/core/files.ts) only
 * stored a Blob URL + uploader. These enums add the lifecycle / access /
 * trust vocabulary the acceptance criteria require (owner+target, server
 * verification, scan/review state, soft-delete with audit).
 */

/**
 * Who created the asset — separates user uploads from admin/system files.
 *
 * Acceptance criteria: "사용자 업로드 파일과 관리자/시스템 생성 파일을 구분할 수 있다."
 * - user:   end-user upload (owner = the uploading user)
 * - admin:  uploaded by an operator/admin (owner = the admin user)
 * - system: generated by the platform (no human owner; owner may be null)
 */
export const fileSourceEnum = pgEnum("file_source", ["user", "admin", "system"]);

/**
 * Access policy (PB-FILE-001 §5.1). Default is `private`; only explicitly
 * whitelisted assets are `public`. The base blob helper's hardcoded
 * `access:"public"` is replaced by branching on this flag in the API layer.
 */
export const fileVisibilityEnum = pgEnum("file_visibility", ["public", "private"]);

/**
 * Upload lifecycle (PB-FILE-001 §5.4).
 * - pending: client-upload token issued, bytes not yet confirmed (orphan TTL applies)
 * - ready:   `onUploadCompleted` confirmed, server-verified metadata stored
 * - failed:  upload/verification failed; row kept for cleanup
 * - deleted: soft-deleted (also recorded via deletedAt/deletedBy for audit)
 */
export const fileStatusEnum = pgEnum("file_status", ["pending", "ready", "failed", "deleted"]);

/**
 * Malware / safety scan state. Separate from upload status so a `ready` file
 * can still be quarantined. `skipped` = scanning not configured for this type.
 */
export const fileScanStatusEnum = pgEnum("file_scan_status", [
  "pending",
  "clean",
  "infected",
  "error",
  "skipped",
]);

/**
 * Content moderation / editorial review state for user-generated content.
 * Supports Apple/Google UGC safety requirements for community features.
 * `not_required` = asset type does not need moderation (default).
 */
export const fileReviewStatusEnum = pgEnum("file_review_status", [
  "not_required",
  "pending",
  "approved",
  "rejected",
]);
